# Generated by Django 5.0.2 on 2024-02-25 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="T_Expense",
            fields=[
                ("expense_id", models.AutoField(primary_key=True, serialize=False)),
                ("expense_group_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("create_on", models.DateTimeField(auto_now_add=True)),
                ("create_user", models.CharField(max_length=255)),
                ("update_on", models.DateTimeField(auto_now=True)),
                ("update_user", models.CharField(max_length=255)),
                ("update_cnt", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="T_Burden_User",
            fields=[
                ("burden_id", models.AutoField(primary_key=True, serialize=False)),
                ("burden_user_id", models.IntegerField()),
                ("create_on", models.DateTimeField(auto_now_add=True)),
                ("create_user", models.CharField(max_length=255)),
                ("update_on", models.DateTimeField(auto_now=True)),
                ("update_user", models.CharField(max_length=255)),
                ("update_cnt", models.IntegerField(default=0)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GoDutchApp.t_expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="T_Expense_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_on", models.DateField(null=True, verbose_name="支払日")),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="支払金額"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("0", "飲食代"),
                            ("1", "施設利用料"),
                            ("2", "ガソリン代"),
                            ("3", "高速代"),
                            ("4", "宿泊代"),
                            ("5", "交通費"),
                            ("6", "備品代"),
                            ("7", "消耗品代"),
                            ("8", "その他"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="商品種別",
                    ),
                ),
                (
                    "payee",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="支払先"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "現金"),
                            ("1", "カード"),
                            ("2", "PayPay"),
                            ("3", "au pay"),
                            ("4", "Suica"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="支払方法",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="メモ"
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GoDutchApp.t_expense",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="支払者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_group_id", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
