# Generated by Django 5.0.2 on 2024-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GoDutchApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="t_expense_detail",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, null=True, verbose_name="支払金額"
            ),
        ),
    ]
