# Generated by Django 5.0.2 on 2024-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GoDutchApp", "0002_alter_t_expense_detail_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="t_burden_user",
            name="delete_flg",
            field=models.BooleanField(default=False),
        ),
    ]
