# Generated by Django 5.0.2 on 2024-03-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GoDutchApp", "0003_t_burden_user_delete_flg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="t_expense_detail",
            name="payer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="GoDutchApp.t_burden_user",
                verbose_name="支払者",
            ),
        ),
    ]
