# Generated by Django 5.0.2 on 2024-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GoDutchApp", "0005_remove_t_burden_user_delete_flg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="t_burden_user",
            name="delete_flg",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="t_burden_user",
            name="burden_user_id",
            field=models.IntegerField(),
        ),
    ]
